name: CI

on:
  push:
    branches:
      - production  # Kích hoạt khi có pull request vào nhánh production

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: letranthienthang/devops:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: deploy
        run: |
          SECRET_MESSAGE=$(echo "Secret message" | openssl enc -aes-256-cbc -base64 -salt -out secret.txt -k your_password -pbkdf2)
          
          curl -X POST your_url_here \
            -H "Content-Type: application/json" \
            -d '{"data":"'"$SECRET_MESSAGE"'"}'